### ISSUE TITLE
Update the picture order in Survey123

### ISSUE THREAD

**Issue by ladejobi** [kcigeospatial/Inlet-Field-and-Web-App-Configuration#11]
![image](https://user-images.githubusercontent.com/8458252/52511688-232eb900-2bcf-11e9-9012-ad22051e8b96.png)

**Comment by talllguy** [comment]
✅ The Inlet Cleaning form in Survey123 is updated to 2.1. AGO Link: https://arcg.is/1zvzXb

![image](https://user-images.githubusercontent.com/1827881/52589513-fb2c9900-2e0c-11e9-8f0a-ebf04c499142.png)
