### ISSUE TITLE
Add a Pipe Condition Category on S123

### ISSUE THREAD

**Issue by ladejobi** [kcigeospatial/Inlet-Field-and-Web-App-Configuration#12]
Before the post cleaning photo please add a pipe condition section.  It should include a checkbox for the options that we think may be an issue as well as an other option to include written comments

- [x] Pipe stable condition
- [x] Pipe blocked
- [x] Pipe failing / unstable
- [x] Other

[Update 2/11/2019](https://github.com/kcigeospatial/Inlet-Field-and-Web-App-Configuration/issues/12#issuecomment-462420989):

- [x] set it so there is a comment for pipe condition that is only required when “Other” is picked

**Comment by talllguy** [comment]
Ah, I see now. This is in liue of #9.

**Comment by talllguy** [comment]
I'm going to assume that by "checkbox" she meant _radio button_. In other words, the user can only pick one of these options. If that is not the case we can revise.

**Comment by talllguy** [comment]
Sent an email with questions to Makeda and @ladejobi.

> Makeda: a few questions
>  
> **Pipe Condition Section**
> 
> - Is this required? I am assuming yes.
> - Is this a select one or select multiple? I assume one, since some of these are mutually exclusive. I will set it so there is a comment for pipe condition that is only required when “Other” is picked.
> - Is this for the outflow pipe only? Some inlets have an inflow from another location.
>  
> Send me any known field users or direct them to the group where they can request membership. I set you as a group manager so that you can approve anyone, or add anyone. Here’s a link to the group: https://arcg.is/1imOaC

**Comment by talllguy** [comment]
Added in _Connect_
![6nx6cwqd5g](https://user-images.githubusercontent.com/1827881/52584031-0c6ea900-2dff-11e9-8f31-8363da8d3c95.gif)

**Comment by talllguy** [comment]
✅ The Inlet Cleaning form in Survey123 is updated to 2.1. AGO Link: https://arcg.is/1zvzXb

![image](https://user-images.githubusercontent.com/1827881/52589513-fb2c9900-2e0c-11e9-8f0a-ebf04c499142.png)
