### ISSUE TITLE
Update Skip Inlet workflow

### ISSUE THREAD

**Issue by ladejobi** [kcigeospatial/Inlet-Field-and-Web-App-Configuration#13]
Skip Inlet.  Some of the options seem to be repetitive.  Please provide the following options for skip inlet

- Inlet not found
- Grate damaged
- Dangerous site condition
- Grate welded / bolted
- Inaccessible site
- MOT restrictions
- Other

**Comment by talllguy** [comment]
@ladejobi should `Other` have a required box that asks what _other_ means?

**Comment by talllguy** [comment]
@ladejobi per #9 "Pipe Blocked" should also be on this list it seems. Do you agree?

**Comment by ladejobi** [comment]
@talllguy Yes to both.

**Comment by talllguy** [comment]
Original domains for reference


list_name | name | label
-- | -- | --
D_II_SKIP | not_found | Inlet not found
D_II_SKIP | removed | Inlet removed
D_II_SKIP | reconstructed | Inlet reconstructed
D_II_SKIP | not_accessible_equipment | Equipment needed
D_II_SKIP | not_accessible_danger | Dangerous condition
D_II_SKIP | not_accessible_mot | MOT required
D_II_SKIP | not_accessible_conflict | Site conflict
D_II_SKIP | other | Other

**Comment by talllguy** [comment]
Updated the domain for the skipping. Here's a demo in Connect:

![qkqhdsvbpl](https://user-images.githubusercontent.com/1827881/52587726-a850e280-2e08-11e9-8282-ed1fc2975dde.gif)

## New D_II_SKIP

list_name | name | label
-- | -- | --
D_II_SKIP | not_found | Inlet not found
D_II_SKIP | grate_damage | Grate damaged
D_II_SKIP | not_accessible_danger | Dangerous site condition
D_II_SKIP | grate_weld_bolt | Grate welded or bolted
D_II_SKIP | not_accessible | Inaccessible site
D_II_SKIP | not_accessible_mot | MOT restrictions
D_II_SKIP | other | Other

**Comment by talllguy** [comment]
✅ The Inlet Cleaning form in Survey123 is updated to 2.1. AGO Link: https://arcg.is/1zvzXb

![image](https://user-images.githubusercontent.com/1827881/52589513-fb2c9900-2e0c-11e9-8f0a-ebf04c499142.png)
