### ISSUE TITLE
Make view of the inlets that is read only

### ISSUE THREAD

**Issue by talllguy** [kcigeospatial/Inlet-Field-and-Web-App-Configuration#17]
The field map currently uses the edit FC and should be migrated to a read-only version. 

`cdb6c1b9029c4014b83b916d6a6ab011`

- [ ] publish a read-only view
- [ ] update the field web map

**Comment by makedadrake** [comment]
Please provide an update on the status of this item

**Comment by talllguy** [comment]
This is now updated with recent changes to the field map
