### ISSUE TITLE
Adding new structure

### ISSUE THREAD

**Issue by makedadrake** [kcigeospatial/Inlet-Field-and-Web-App-Configuration#21]
The only structure that should be able to be added is an inlet.  The mapping only showes inlets.  The app does not show if any other structure is in SHA's inventory. The mapping would not show if a endwall is in the inventory, the field crew will not know if a endwall needs to be added or not.

**Comment by talllguy** [comment]
Level of effort on this one: about 30 minutes.
ETA: Today (19 Feb 2019)

Just need to update the domain/types of structures that can be added.

**Comment by talllguy** [comment]
I've reduced the possible structures that can be created to Inlet and Unknown Inlet†.
![image](https://user-images.githubusercontent.com/1827881/53044462-16c12080-3459-11e9-9509-daf50678a5b7.png)

While doing this, I also reduced the number of possible attribute fields to update. Here's the current list of attributes the user can update with a description of each. This should lower the burden on the user, as only the most pertinent fields are displayed.


Display Name | Field Name | Type | Use in Inlet Cleaning Program
-- | -- | -- | --
GIS Object ID | OBJECTID | ObjectID | Machine field - not user edited
SHA Structure Number | SHA_STR_NO | String | SHA Structure number, only if known
SHA Structure Type | STR_TYPE | String | User can only create Inlet types unless they change this
Function Class | FUNC_CLASS | String | Function Class (always inflow)
Date Verified | DATE_VER | Date | The field user should set this to today
Feature Status | FEAT_STATUS | String | Status is always existing
Additional Structure Comments | COMMENTS | String | Structure comments about the structure in general
Designation | IN_DESG_IN | String | Inlet designation, e.g. J Inlet
Length | IN_INLET_LEN | String | Standard NPDES lengths
Material | IN_MTRL_IN | String | Inlet material
Top of Grate | IN_TOP_OF_GRT | Double | Inlet's TOG
Comments | IN_COM_IN | String | Inlet specific comments
Created Date | FLD_CREATIONDATE | Date | Editor Tracking - Automatic
Creator | FLD_CREATOR | String | Editor Tracking - Automatic
Edited Date | FLD_EDITDATE | Date | Editor Tracking - Automatic
Editor | FLD_EDITOR | String | Editor Tracking - Automatic
GIS Global ID | GLOBALID | GlobalID | Machine field - not user edited



† UNK IN is used if the user is unsure that this structure is an inlet but assumes it is.

**Comment by talllguy** [comment]
@makedadrake let me know if you have any comments or concerns. If not, we can close this.

**Comment by makedadrake** [comment]
Lets leave off unknown structure.  It will be verified before it is put into HHD inventory.  All new structures are thought to be an inlet.  If it is in question they can add that to the comments.

**Comment by talllguy** [comment]
Agreed the unknown structure is not needed. I've removed the ability to create one.
