### ISSUE TITLE
Field App Bookmark locations

### ISSUE THREAD

**Issue by makedadrake** [kcigeospatial/Inlet-Field-and-Web-App-Configuration#22]
While in the field app on a tablet or phone there is no way to add or remove bookmark locations.

**Comment by talllguy** [comment]
There is a way. I'll detail this later today (19 Feb 2019).

**Comment by talllguy** [comment]
To add a bookmark on mobile, just tap and hold the map to drop a pin.

Then, scroll to the Add to My Places button to add a mobile bookmark. The only way to add bookmarks to the "Bookmarks" screen is by editing the web map.

## 1 Drop Pin

![drop_pin](https://user-images.githubusercontent.com/1827881/53046289-b7194400-345d-11e9-9d2c-91c78c5e117c.jpg)

## 2 Add to my places

![my_places](https://user-images.githubusercontent.com/1827881/53046342-ce583180-345d-11e9-9d5b-81d066a05a6b.jpg)
