### ISSUE TITLE
Delete Work Order Areas

### ISSUE THREAD

**Issue by talllguy** [kcigeospatial/Inlet-Field-and-Web-App-Configuration#24]
Per outcomes of the 3/20 meeting, the work order areas should be deleted.

@makedadrake there were only four work order areas in the dataset as of 3/20. You can open [the dataset here and see them all](https://arcg.is/OKDaf). they're quite small and centered around two intersections.

Emails detailed below

> Kristen L. on 3/21
> Since we will not be utilizing the assignment tool at this time, we agreed to remove all assignment shapes/work order shapes that you created.  It looked like there may only be 4 small test areas still in there.  Please remove those and let us know when you are finished.  Elliott will be turning the assignment tool off when you are finished to avoid confusion.

>> Makeda on 3/21
>> From the email below I am looking for the assignment shapes that are in the assignment app.  When I view the assignments in the status view app I 'm not seeing any shapes.  Please let me know what assignment shapes are still being shown.

**Comment by makedadrake** [comment]
Can the work area tool be turned off in the field app only?  That allows for the shape tool to be used in the assignment app and not be seen in the field app.

**Comment by talllguy** [comment]
Given how the new web tool is multi-functional, we cannot add the ability to create or add anything within it. This is because editing is open to anyone with access, and the redesigned web app is meant to a wider audience.

**Comment by talllguy** [comment]
Work order area editing ability and layer removed from the map.
