### ISSUE TITLE
Update Inlet symbology and enforce the same symbology in the field tool

### ISSUE THREAD

**Issue by talllguy** [kcigeospatial/Inlet-Field-and-Web-App-Configuration#29]
Red – Inlets with debris >25% (needs cleaning)
Blue – Everything else
Green – Inlets with a status of Cleaned
Yellow – Skipped (not mentioned in UAT but later deemed necessary

- [x] Update program app
- [x] Update field app
- [x] Change schema?

**Comment by talllguy** [comment]
Some recent updates:

1. The recent cleaned status will change in the future where the date becomes dependent on a table listing the time each inlet cleaning is good for. For now, the above works.
2. There's an additional logic to add out of a team meeting today. RECENT_CLEANED_PLUS_PIPE - any inlet where PIPE_CLEANED is 'cleaned' AND CLI_INSPECTION_DATE is in the past 6 months. This is dependent on #37

**Comment by johnshiu** [comment]
The ETL_PROGRAM_CATEGORY field has been added, and the ICP has been refreshed manually. You should see some of these values showing up. Please let me know if there appear to be any logic issues.

**Comment by talllguy** [comment]
@johnshiu thanks, I see the field but the logic does appear to be off. I edited the comment above to simplify but to further break out the logic, here's a table. Does this make sense?


logic | result
-- | --
PRE_PERCENT_CHAMBER_FULL >= 25 AND   none of these other statuses apply | TO_CLEAN
CLI_CLEAN_STATUS = 'skipped' AND   CLI_INSPECTION_DATE is between today and six months ago | RECENT_SKIP
CLI_CLEAN_STATUS = 'cleaned' AND   CLI_INSPECTION_DATE is between today and six months ago | RECENT_CLEANED
CLI_PIPE_CLEANED = 1 AND   CLI_INSPECTION_DATE is between today and six months ago | RECENT_CLEANED_PLUS_PIPE

**Comment by johnshiu** [comment]
@talllguy, hmm, I think that all lines up with what I have in the script. Here is what we have in the ICP for non-null ETL_PROGRAM_CATEGORY:
![image](https://user-images.githubusercontent.com/6249952/56158940-6c193a00-5f91-11e9-8ae7-9433f50db1a1.png)

Does anything there look incorrect?

**Comment by talllguy** [comment]
@johnshiu those look right. In the data on NPDES though there are only six inlets set to TO_CLEAN and none with any other categories. There should be many thousands set to TO_CLEAN and just a few with the other statuses.

**Comment by johnshiu** [comment]
@talllguy, ah ok, I think the removal of the inspection date logic for the TO_CLEAN should have fixed it. Please try it again; there should be over 4000 now.

**Comment by talllguy** [comment]
Wonderful, it’s working now! I’ll add some test ones that should trigger the various statuses tonight so they’ll appear tomorrow. What happens if I delete a survey? Will it clear the CLI ?

--
Elliott Plack, Senior Business Analyst
Geospatial Solutions • KCI Technologies, Inc.

w: (410) 891-1750
m: (410) 206-6448

📧📲



On Mon, Apr 15, 2019 at 3:32 PM -0400, "John Shiu" <notifications@github.com<mailto:notifications@github.com>> wrote:


@talllguy<https://github.com/talllguy>, ah ok, I think the removal of the inspection date logic for the TO_CLEAN should have fixed it. Please try it again; there should be over 4000 now.

**Comment by johnshiu** [comment]
Hmm, if you delete a survey, it will clear most of the CLI fields except the CLI_CLEAN_STATUS field, which will preserve its clean status from before the refresh. It will only update if a new survey is submitted in AGOL, which then overwrites whatever is in the CLI_CLEAN_STATUS field. I think this logic is there to make sure that subsequent, new inspections will supersede what is in the field, while at the same time preserving any edits to the ICP via the feature service until a new survey is submitted.

**Comment by talllguy** [comment]
Everything in my testing on this is working great. I'll double check after it runs tonight but everything is operating as expected.

**Comment by talllguy** [comment]
@johnshiu after the overnight refresh, one small bit of the logic is not working: the `RECENT_CLEANED_PLUS_PIPE` part.

Structure Number 0300201.002 should have this status.

Here's why:
![chrome_WUIoCVFO9O](https://user-images.githubusercontent.com/1827881/56202297-bb527f80-6010-11e9-9c32-a6b65c1a45bf.png)

The highlighted field is aliased for `CLI_PIPE_CLEANED`. When it is 1, `ETL_PROGRAM_CATEGORY` should equal `RECENT_CLEANED_PLUS_PIPE`

**Comment by talllguy** [comment]
@johnshiu Hold that thought. There is another tweak. Let me close this issue and start a new one to better cover this.
