### ISSUE TITLE
Add new fields from cleaning S123 to ICP

### ISSUE THREAD

**Issue by talllguy** [kcigeospatial/Inlet-Field-and-Web-App-Configuration#37]
The new fields in the Survey123 feature service to be added to ICP and synced are:

- PIPE_CONDITION
- PIPE_CONDITION_COM
- PIPE_CLEANED
- PIPE_CLEANED_LIN_FT

**Comment by johnshiu** [comment]
These fields have been added to the ICP. They will be refreshed upon the next AGOL sync tonight.

**Comment by talllguy** [comment]
Validated the fields are added. They look good. Thanks!
