### ISSUE TITLE
Some Cleaned Inlets remain blue in the tracking map

### ISSUE THREAD

**Issue by talllguy** [kcigeospatial/Inlet-Field-and-Web-App-Configuration#43]
Good morning Kristin,

I noticed that two inlets I did a few days ago are still blue on the map and haven’t changed to the proper color. I double checked and I see the surveys are in my outbox in Survey123. 

Inlet 1601962.01
38.887510°N 76.889315°W

Inlet 1601963.003
38.887540°N 76.888411°W

Let me know if there is anything you need me to do on my end. 

All the best,
Tyler

**Comment by talllguy** [comment]
I spoke with @johnshiu about this.

> Hi Elliott,
> 
> I think it’s because program category ETL is looking for CLI_PIPE_CONDITION to be ‘stable’ and the CLI_CLEAN_STATUS = ‘cleaned’; however, there are several cases where the CLI_CLEAN_STATUS = ‘cleaned’ and the CLI_PIPE_CONDITION is null. When it doesn’t fit any category, it defaults to ‘CLEANING_NEEDED’. 
> 
> Should we allow CLI_PIPE_CONDITION to be null when setting to RECENT_CLEANED?
> 
> Thanks!
> John

**Comment by HollySchuelerKCI** [comment]
This issue has been resolved.
