### ISSUE TITLE
Turn off assignment tracking trigger

### ISSUE THREAD

**Issue by talllguy** [kcigeospatial/Inlet-Field-and-Web-App-Configuration#44]
The early requirement to keep track of updates to the work order number is no longer valid. Therefore, we can turn off that trigger and related table, unless it could be used for other fields. @johnshiu what do you think? Could we use it as an audit log for whenever the #41 ETL runs?

**Comment by johnshiu** [comment]
Hmm, I would recommend just disabling it altogether for now. The ETL refresh is already logged in a separate table, so we don't need the trigger to track it as well.

**Comment by johnshiu** [comment]
The trigger has been disabled; I have left the existing tables for now, however, in case they want to resurrect some sort of edit tracking.
