### ISSUE TITLE
Inlets along MD-5 not syncing

### ISSUE THREAD

**Issue by talllguy** [kcigeospatial/Inlet-Field-and-Web-App-Configuration#45]
Several inlets along MD-5 south of DC are not having their ETL_PROGRAM_CATEGORY updated. @johnshiu can you check the status of it?

Here's an example on that should be cleaned/green

  | Source Inlet | Survey123
-- | -- | --
Structure No | 1600474.01 | 1600474.01
Structure ID | d5928981-b811-4e43-be65-47ed4d01b01c | d5928981-b811-4e43-be65-47ed4d01b01c
Global ID | {16AF9127-75D8-4CAF-89B6-676C2DDC2B1F} | 16af9127-75d8-4caf-89b6-676c2ddc2b1f
Clean Status | Cleaning Needed | cleaned

Here's a few more:

![image](https://user-images.githubusercontent.com/1827881/59610451-6b169d00-90e7-11e9-99c6-a598a849a00d.png)

**Comment by johnshiu** [comment]
@talllguy, I think that survey hasn't been synced yet. The creation date is:

CreationDate: | 6/17/2019 12:40:26 PM
-- | --
Creator: | amanda.looper

I think that's UTC time, so 8:40 AM today, our time. It should be captured in the next overnight sync tonight.

**Comment by talllguy** [comment]
@johnshiu there are some others that are further down on US 301 that were inspected 6/12 but are still not showing. However, I see an issue with the related keys with these. Stakeholder first reported the issue on Thursday last week.

![image](https://user-images.githubusercontent.com/1827881/59621209-c901af80-90fc-11e9-83c8-7498c09c8fb8.png)

For these ones, the structure ID and number are both null or invalid! This must be a source data issue? Luckily I did include that Global ID in the matching so we can still match the inspections to inlets with no attributes. **Can you make it so that the ETL script is based on the assumed referential match from {GLOBALID} to {REL_GLOBALID}?** This is the only reference that we're guaranteed to have. The structure number or structure ID are only good when they're populated. If the ETL already uses the Global ID, then there is a problem. You can use `581b298a-b925-43f9-83bc-f4fb97454742` as an example where both the Survey123 REL_GLOBALID and the ICP GLOBALID are that value.

The underlying issue here is why these inlets have all null attributes. They could be newly entered? I'll investigate further.

**Comment by talllguy** [comment]
I took a look at this area on NPDES prod and all the inlets are there with attributes. Is it possible the using the Global ID may not be the best way to go since it may not be the same Global ID as the source inlet? I hadn't considered that possibility.

![image](https://user-images.githubusercontent.com/1827881/59622946-f3556c00-9100-11e9-8638-f9f7682231cf.png)

**Comment by talllguy** [comment]
Perhaps we need "Source Global ID"

**Comment by johnshiu** [comment]
For the ones with null structure IDs, we can use the REL_GLOBALID field to relate them with the new INLET_FOR_INSPECTION features that have no structure ID yet. I previously only related the pre-inspection results, not the cleaning inspection results, so this required a script update.

I have re-run the refresh with the updates, and they are now showing the correct cleaning symbology:

![image](https://user-images.githubusercontent.com/6249952/59627773-0b32ed00-910d-11e9-8ee8-128c84658d49.png)

**Comment by talllguy** [comment]
@johnshiu to confirm, the `REL_GLOBALID` is now the FK for both an ICP†-initiated **and** field inlet-initiated inspections? These are the two possible inspections that can appear in the app. Is this first hierarchy accurate?

![image](https://user-images.githubusercontent.com/1827881/59681259-7cbc7b00-91a1-11e9-9b67-b323ccc5dd92.png)

This would be the **old hierarchy** as I understand it:
![image](https://user-images.githubusercontent.com/1827881/59681296-965dc280-91a1-11e9-9ab9-0fc1240daaa1.png)

**Comment by johnshiu** [comment]
@talllguy, the old hierarchy is actually still the one being used. I only updated the association on the field inlets that do not have a valid STRUCTURE_ID because they are inserted separately into the ICP. The ones with the valid STRUCTURE_ID are associated with the NPDES.STRUCTURES feature class using the STRUCTURE_ID when inserted into the ICP.

**Comment by talllguy** [comment]
@johnshiu thanks! In this case, how did the inlets not have any of their production attributes (number, type, etc.) until you did the sync yesterday?
