### ISSUE TITLE
Include District number in Survey123 data

### ISSUE THREAD

**Issue by talllguy** [kcigeospatial/Inlet-Field-and-Web-App-Configuration#46]
@HollySchuelerKCI requests that we include the district number in the inspected data

**Comment by talllguy** [comment]
@HollySchuelerKCI @klangway this change is live as v2.4.4 of the form. You can notify the field teams to make the update. The collector map has already been modified to pass the district information along.

**Comment by talllguy** [comment]
Added this to both online and offline maps.

**Comment by HollySchuelerKCI** [comment]
@talllguy I noticed that the MDOT District field is not populated in the program application.

**Comment by talllguy** [comment]
@HollySchuelerKCI I added it to the Survey123 form and it will populate going forward (as long as the users are on v2.4.4, but it does not reverse populate. I'm working on that part.

**Comment by talllguy** [comment]
@HollySchuelerKCI I updated all the District numbers that I could. The ones at MES or Null Island #50 will need to be handled to do the rest

**Comment by talllguy** [comment]
Implemented at 2.4.8
