### ISSUE TITLE
Firm or Team Separation

### ISSUE THREAD

**Issue by talllguy** [kcigeospatial/Inlet-Field-and-Web-App-Configuration#48]
An enhancement to consider is making the maps specific to their user (contractor or state forces) to help with QC.

**Comment by talllguy** [comment]
I think we should add a "CLEAN_TEAM" field with the following possibilities (dropdown) to start.

- D1 State Forces
- D1 State Forces
- D1 State Forces
- D1 State Forces
- D1 State Forces
- D1 State Forces

**Comment by talllguy** [comment]
@HollySchuelerKCI @klangway how does this list of teams look?

**Comment by talllguy** [comment]
And, can you give me a list of who is on what team?

**Comment by HollySchuelerKCI** [comment]
@talllguy This list looks good. We may need to update once D5 receives NTP

**Comment by HollySchuelerKCI** [comment]
MES:

Coplin | Jonathan
-- | --
Pullen | Tyler
Iacangelo | Rachel
Cullen | Shaun
Barnett | Joanna
Riesett | Jessica
Looper | Amanda
Mallonee | Amy
Anderson | Brady
Kozloski | Maggie


DBI:

Dixon | E'Carl
-- | --
Dixon | John
Anderson | Matthew
Tunstall | James
Whilte | Charles
Lane | Darrell
Harris | Andre
Holston | Christopher
Ford5 | Floyd
Hamilton | Blake

**Comment by talllguy** [comment]
@HollySchuelerKCI how about Dirk Lueters and Salvador Campos?

**Comment by HollySchuelerKCI** [comment]
@talllguy Dirk and Salvador are with state forces.

**Comment by HollySchuelerKCI** [comment]
@talllguy Please create firm TriState with the following users:
•	Herman Barber
•	Paul Little 
•	DaJuane Goode
•	Ed Jefferson

**Comment by HollySchuelerKCI** [comment]
@talllguy  Can you confirm that joanna.barnett is assigned MES?

**Comment by talllguy** [comment]
We did decide not to go down the path of multiple maps (four ish is enough already)
