### ISSUE TITLE
Add QA/QC Fields to Cleaning Data

### ISSUE THREAD

**Issue by talllguy** [kcigeospatial/Inlet-Field-and-Web-App-Configuration#53]
Add QA/QC fields to help @HollySchuelerKCI and @klangway verify cleanings.

### Proposed schema

@HollySchuelerKCI and @klangway please verify that this looks substantial.

Field | Alias | Type | Domain | Length | Description
-- | -- | -- | -- | -- | --
QC_STATUS | QC Status | short | D_QC_STATUS |   | QA/QC Status field with a domain (picklist)
QC_STATUS_COM | QC Status Comment | string |   | 256 | Additional QA/QC comments if desired
QC_STATUS_DATE | QC Status Date | date |   |   | Date of last QA/QC check
QC_INITIALS | QC'er Initials | string |   | 5 | Initials of QA/QC personnel

D_QC_STATUS | Label | Description
-- | -- | --
0 | Complete | Check is complete
1 | Pending | Pending some feedback from field team
2 | Rejected | Rejected, such as a duplicate
9 | Other | Anything else, comment recommended

**Comment by HollySchuelerKCI** [comment]
This appears to be correct. Please await Kristin's confirmation

**Comment by klangway** [comment]
Looks good to me. Thanks!

**Comment by talllguy** [comment]
@johnshiu FYI I'll be adding these fields. They do not need to be pulled to the ICP.

**Comment by talllguy** [comment]
All the fields have been added
