### ISSUE TITLE
Smart Editor Not Available via Pop Up

### ISSUE THREAD

**Issue by HollySchuelerKCI** [kcigeospatial/Inlet-Field-and-Web-App-Configuration#58]
It appears that the Smart Editor will occasionally not be available to the user via the Pop Up window.  See screenshot below:

![image](https://user-images.githubusercontent.com/25441512/60593059-f6429480-9d6f-11e9-9ea6-3209cb3d4f16.png)

**Comment by talllguy** [comment]
While trying to fix #60 I removed the app altogether so I'll need to recreate to fix this. It should appear but might not under certain conditions.

**Comment by HollySchuelerKCI** [comment]
@talllguy Please let me know when the QA/QC App is available for me to use.

**Comment by talllguy** [comment]
@HollySchuelerKCI Since the batch attribute editor isn't working, I think it is high time we get you editing the data in ArcGIS Pro. Is Dave T around today? Maybe he can help you get it installed if applicable.

**Comment by HollySchuelerKCI** [comment]
@talllguy I do have ArcPro installed. Will I now be using that platform for QA/QC?

**Comment by talllguy** [comment]
Yes, that's the plan. Let's meet later and review the workflow.

**Comment by talllguy** [comment]
The QC App is ready now: https://maryland.maps.arcgis.com/home/item.html?id=3516127b072e421fb735caaa095478e4

**Comment by HollySchuelerKCI** [comment]
@talllguy Here are my observations:

- Can you change the default for "filter by map extent"? It is currently "ON" 
- In the Search Bar, can you include search by structure number?
- Can you change the table order to the following:
     - Inspected SHA Struc No
     - Inspected Global ID
     - Creator (Need to add)
     - Inspection Date
     - Clean Status
     - Skip Inlet
     - Other Skip Reason
     - Override a PreCleaning Photo
     - PreCleaning Comment
     - Pipe Condition Comment
     - Post Cleaning Comment
     - Pipe Condition
     - Pipe Cleaned
     - Linear Feet
     - MDOT SHA District
     - Maintenance Shop
     - Inspected Structure ID
     - Form Version
     - form start
     - form end
    - QC Status
     - QC Comment
     - QC Date
     - QC Initials

**Comment by HollySchuelerKCI** [comment]
@talllguy Please add team to the above list

**Comment by HollySchuelerKCI** [comment]
@talllguy Any update on the progress for the above updates to the QC App?

**Comment by talllguy** [comment]
@HollySchuelerKCI I fixed all of the above issues. Reopen if anything is off!
