### ISSUE TITLE
Drop EXIF GPS Fields

### ISSUE THREAD

**Issue by talllguy** [kcigeospatial/Inlet-Field-and-Web-App-Configuration#62]
The GPS Data fields are an annoyance to project users and lack a purpose. They were a part of the original requirements but have not been needed. In Survey123 update v2.4.8, I stopped the fields from being populated in S123, but they remain in the schema.

This issue serves as a proposal to drop these fields.

### Field Users

All submitted cleaning are from S123 v2.4.8 as of July 1, 2019. Any users that haven't updated would be **unable to submit surveys in the older versions once these fields are dropped**, so it is imperative that all users submit any drafts and delete the old surveys prior to this action.

### ETL

If these fields are copied by the ETL, there could be an impact. @johnshiu please detail.

**Comment by talllguy** [comment]
CC: @HollySchuelerKCI @klangway

**Comment by johnshiu** [comment]
@talllguy, the EXIF fields are not in the SHA schema, so they can be dropped in AGOL when needed.

**Comment by talllguy** [comment]
This is completed. 110 fields removed!
