### ISSUE TITLE
Refactor Skipped Inlets where reason is Other

### ISSUE THREAD

**Issue by talllguy** [kcigeospatial/Inlet-Field-and-Web-App-Configuration#63]
Anytime we have a text field in a field form that gets a lot of repetitive responses, we should add radio buttons or check boxes (a domain) to speed input and improve overall UX. An email from @klangway reminded me that most of the inlets where `SKIP_INLET` is set to _Other_ are done so because the inlet was already clean. In update 2.4.8 we added a _Not Dirty_ option to the skip reasons to reduce the number of _Other_ responses.

I've refactored most of the inlets set to _Other_ to _Not Dirty_ based an an analysis of the data. There were 795 skipped inlets with a reason of _Other_ prior to this analysis. I set 764 (96%) to _Not Dirty_ (see below). There are 31 _Other_ ones remaining that we may want to convert into more radio buttons. Please review.

## Other Analysis

Reason | Number | New Skip Reason
-- | -- | --
Inlet clean | 431 | not_dirty
Inlet was clean | 2 | not_dirty
Inlet was clean. | 230 | not_dirty
anything else containing "clean" | 101 | not_dirty
other | 31 | -
**Total** | **795** | -

## Remaining Other

Other   Reason | Ref | Creation Date | Creator | Version
-- | -- | -- | -- | --
Bridge inlet clear | 1603137.001 | 6/19/2019 | joanna.barnett | 2.4.3
Bridge inlet clear | 1603133.001 | 6/19/2019 | joanna.barnett | 2.4.3
Full of standing water | 1601803.002 | 6/19/2019 | amy.mallonee | 2.4.2
Full of standing water | {369E5972-F70C-44AF-BF8E-A74DF3A9AD88} | 6/19/2019 | amy.mallonee | 2.4.2
Full of water | 1601831.002 | 6/20/2019 | amy.mallonee | 2.4.2
Full of water | {F4028D61-963F-4E1B-A629-A7350CE6900E} | 6/20/2019 | amy.mallonee | 2.4.2
Full of water from rain event in past   24hrs. Cleaning would fill up truck. | 1600574.018 | 6/11/2019 | tyler.pullen | 2.4.3
Grate paved with asphalt in inlet | 1601753.002 | 6/17/2019 | amy.mallonee | 2.4.2
High water flow coming from adjacent   inlet made it impossible to clean. | 1601840.003 | 7/3/2019 | tyler.pullen | 2.4.8
Inlet appears to be new or under   construction. | {ECA58F32-D312-4CEA-AE65-4D9376CFCEF8} | 6/11/2019 | amanda.looper | 2.4.3
Inlet clea n | {1A7E398D-7953-4502-B4D9-BFAB42D9D952} | 5/30/2019 | tyler.pullen | 2.4.3
Inlet full of water | 1601829.004 | 6/20/2019 | amy.mallonee | 2.4.2
Inlet grates would not come loose.   Pressure washer was used to spray down debris inside of the inlet. No vacuum   was used. | 1602699.002 | 5/9/2019 | amanda.looper | 2.4.2
Inlet is covered in tree stumps/weeds.   Weed whacker needed to complete this inlet. | 1602326.002 | 6/7/2019 | amanda.looper | 2.4.3
Inlet is full of water, but minimal   debris. | 1600440.002 | 6/19/2019 | amanda.looper | 2.4.3
Inlet is under construction. See photos. | 1602273.002 | 6/4/2019 | amanda.looper | 2.4.3
Inlet skipped due to jersey wall over   grate | 1603144.012 | 6/10/2019 | shaun.cullen | 2.4.2
Large dump truck broken down in front of   inlet. | 1600438.013 | 6/19/2019 | amanda.looper | 2.4.3
Pipe clear, but large wood pieces inside   chamber | 1600993.014 | 5/10/2019 | tyler.pullen | 2.4.2
Pipe outfall | 1602584.002 | 5/17/2019 | amy.mallonee | 2.4.2
Pipe outfall | 1602594.002 | 5/17/2019 | amy.mallonee | 2.4.2
Pipe seems to have collapsed inside inlet | 1601964.013 | 5/14/2019 | tyler.pullen | 2.4.2
Skipped due to jersey wall on grates | 1603144.005 | 6/10/2019 | shaun.cullen | 2.4.2
Skipped due to jersey wall on top of   grates | 1603144.007 | 6/10/2019 | shaun.cullen | 2.4.2
Standing water but no sediment or debris   in inlet | 1601727.003 | 6/19/2019 | amy.mallonee | 2.4.2
Steel plate located over top of inlet   grate. We did not attempt to remove the steel plate. | 1602675.002 | 5/7/2019 | amanda.looper | 2.4.2
This inlet is full of water. In addition,   it appears there is asphalt inside of the inlet. | 1600475.024 | 6/21/2019 | amanda.looper | 2.4.3
To much water flowing back into inlet. | 1603144.021 | 6/10/2019 | shaun.cullen | 2.4.2
To much water in inlet. Possible blockage   at outfall | 1603144.019 | 6/10/2019 | shaun.cullen | 2.4.2
Unable to get manhole cover off | 1602017.002 | 5/9/2019 | tyler.pullen | 2.4.2
Water in inlet. Possible blockage at   outfall | 1603144.016 | 6/10/2019 | shaun.cullen | 2.4.2

**Comment by HollySchuelerKCI** [comment]
@talllguy Another selection would be Standing Water Inside Inlet.

**Comment by talllguy** [comment]
Good idea, I'll add that to the list.

**Comment by talllguy** [comment]
All of the above are now added.
