### ISSUE TITLE
Inlet Cleaning Program App - District Filter 

### ISSUE THREAD

**Issue by HollySchuelerKCI** [kcigeospatial/Inlet-Field-and-Web-App-Configuration#64]
Using the Inlet Cleaning Program App, the user is unable to filter by district.

Steps to Replicate:
1. Click the Filter Icon
2. Select District number (ie. District 3)
3. Turn Filter 'ON'
4. Map does NOT filter based on district

![image](https://user-images.githubusercontent.com/25441512/61734907-d5f36d80-ad50-11e9-94b1-d88d1ddbd625.png)

**Comment by talllguy** [comment]
Holly, that app only filters the the ICP data. To filter the inspections directly, use the dashboard. I’d like to stop maintaining two apps. See if you can do your workflow in the dashboard and then we can take this app down. It only exists because it was built for the assignment workflow.

**Comment by HollySchuelerKCI** [comment]
@talllguy Thank you for clarifying. Kristin and I will be showing the program app to D5 tomorrow morning. I will discuss with her the use of the dashboard for the districts and phasing out the program app.

**Comment by talllguy** [comment]
Added the district filter to the program app. I also clarified the names of the filters to show which goes with what. 
![image](https://user-images.githubusercontent.com/1827881/68125621-f7cbc700-fedf-11e9-977c-279d28ae00d1.png)
