### ISSUE TITLE
Inlet Cleaning Field App - Structure Number Bug

### ISSUE THREAD

**Issue by HollySchuelerKCI** [kcigeospatial/Inlet-Field-and-Web-App-Configuration#68]
Per email from D5 on 10/15/2019: Along MD 174, there are structures from the NPDES database that do NOT have a structure number. There have been several structures that do not have a designated number along MD 174.

Should they use the Structure ID from the Debugging Info at the bottom?

**Steps to Replicate:**
1. Open Collector
2. Zoom to the location of Old Quarterfield Rd and MD 174 or 39.146290 N, 76.641407 W.
![image](https://user-images.githubusercontent.com/25441512/66856121-8a68ee00-ef52-11e9-910f-70a3da5f722a.png)
3. Click on the BLUE structure
4. See BLANK Structure number in screenshot below
![image](https://user-images.githubusercontent.com/25441512/66856251-d3b93d80-ef52-11e9-8824-9e2c628a3657.png)
****

**Comment by talllguy** [comment]
@HollySchuelerKCI as you recall, we closed this one via email. Here's the final summary.

![image](https://user-images.githubusercontent.com/1827881/68123938-3495bf00-fedc-11e9-9df8-b08edcf591f0.png)
