### ISSUE TITLE
Set up Github to track bugs and changes for future versions of the app

### ISSUE THREAD

**Issue by talllguy** [kcigeospatial/Inlet-Field-and-Web-App-Configuration#7]
_Item 7 in the 1/25/2019 action item list_

- [x] Setup :octocat: 
- [x] Email Makeda join instructions
- [x] Add Makeda to repo
- [x] 🚀

**Comment by makedadrake** [comment]
Please provide details as to what is remaining for this item.

**Comment by makedadrake** [comment]
Please provide details as to what is remaining for this item.

**Comment by talllguy** [comment]
This is completed.
